export default function EmplyeeProfileTable() {
  return (
    <table>
      <thead>
        <th>Day</th>
        <th>Status</th>
        <th>Arrival Time</th>
        <th>Leave Time</th>
        <th>Working Hour</th>
      </thead>
      <tbody>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
        <tr>
          <td>Feb</td>
          <td>Present</td>
          <td>08:30</td>
          <td>1230</td>
          <td>1230</td>
        </tr>
      </tbody>
    </table>
  );
}
